// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC547iaQAWUsJtujU2boYxILhTc9MJH3Ng',
    appId: '1:761795463174:web:e15ffb2947b1c27312db87',
    messagingSenderId: '761795463174',
    projectId: 'library-48a97',
    authDomain: 'library-48a97.firebaseapp.com',
    storageBucket: 'library-48a97.appspot.com',
    measurementId: 'G-HBCW6HXR2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2YdNvNZze96SrizmTP0XQ0s4ZuRXu0w4',
    appId: '1:761795463174:android:00b338481bd5750312db87',
    messagingSenderId: '761795463174',
    projectId: 'library-48a97',
    storageBucket: 'library-48a97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtnv7xfcsnU4y69wjNqL3PE3m_ugZEaoc',
    appId: '1:761795463174:ios:13ab2de6d7b85d2912db87',
    messagingSenderId: '761795463174',
    projectId: 'library-48a97',
    storageBucket: 'library-48a97.appspot.com',
    iosBundleId: 'com.example.odev',
  );
}
